config/routes.rb
Rails.application.routes.draw do
  get 'searches/index'
  root 'users#index'
  post 'guest_login', to: 'sessions#guest_login'
  
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations' 
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :chats, only: [:show, :create]
  resources :machines
  resources :lap_time_to_races
  resources :parts
  resources :shops
  resources :searches do
    collection do
      get :search
    end
  end

  get 'shops/index'
  get 'parts/index'
  get 'users/index'

end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  mount_uploader :avatar, AvatarUploader
  has_many :machines, dependent: :destroy
  has_many :lap_time_to_races, dependent: :destroy
  has_many :parts, dependent: :destroy

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy, inverse_of: :follower
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy, inverse_of: :follower
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms
  has_many :chats, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable
  validates :name, presence: true
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true, confirmation: true, length: { minimum: 6 }, on: :create
  validates :password_confirmation, presence: true, on: :create

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    protected

    def after_sign_up_path_for(resource)
      user_path(resource)
    end

    private

    def sign_up_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    protected

    def after_sign_in_path_for(resource)
      user_path(resource)
    end

    def guest_sign_in
      user = User.guest
      sign_in user
      redirect_to user_path(user), notice: t('.logged_in')
    end

    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include PartsHelper

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @machine = Machine.new
    @machines = @user.machines
    @part = Part.new
    @parts = @user.parts
    @text_options = %w[ノーマル レブチューン トルクチューン アトミックチューン ライトダッシュ ハイパーダッシュ スプリントダッシュ パワーダッシュ]
    @text_options2 = %w[タイプ１ タイプ２ タイプ３ タイプ４ タイプ５ ゼロ スーパー１ スーパー２ FM スーパーFM FM-A スーパーTZ
                        スーパーTZ-X スーパーX スーパーXX MS MA AR VS VZ]
    @text_options3 = %w[ノーマルシャフト 中空シャフト 強化シャフト]
    @text_options4 = %w[ノーマルプロペラシャフト 中空プロペラシャフト]
    @text_options5 = %w[低摩擦プラベアリング 丸穴ボールベアリング 六角穴ボールベアリング]
    @text_options6 = %w[ノーマルターミナル ゴールドターミナル]
    @text_options7 = %w[レスポンスポンジタイヤ 中空ゴムタイヤ ソフトスリックタイヤ ハードスリックタイヤ バレルタイヤ オフセットとレッドタイヤ ローハイトタイヤ]
    @text_options8 = %w[小径ホイール 大径ホイール スポークホイール Yスポークホイール 5本スポークホイール ナローワンウェイホイール 小径カーボンホイール 大径カーボンホイール]
    @text_options9 = %w[ハイスピードカウンターギヤー 軽量超速ギヤー]
    @text_options10 = %w[17mmアルミベアリングローラー 19mmアルミベアリングローラー プラリング付きベアリングローラー 17mmプラリング付きベアリングローラー
                         19mmプラリング付きベアリングローラー 9mmボールベアリングローラー 11mmボールベアリングローラー 低摩擦プラリングローラー 2段低摩擦プラローラー(13-13mm)
                         2段アルミローラー(13-12mm) 2段アルミローラー(9-8mm) ゴムリング付き２段アルミローラー(13-12mm) 13mmオールアルミベアリングローラー]
    @lap_time_to_races = @user.lap_time_to_races
    set_shop_categories
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    if @user.save
      sign_in(@user)
      redirect_to @user
    else
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params.require(:user).permit(:name, :email, :password, :introduction, :avatar))
      flash[:notice] = "ユーザーIDが「#{@user.id}」の情報を更新しました"
      redirect_to user_path(current_user.id)
    else
      render "edit"
    end
  end

  private

  def set_shop_categories
    @shop_categories = Shop.where(shop_name: %w[株式会社タミヤ 小鹿第一工場 池田工場 第二物流センター]).to_h { |shop| [shop.shop_name, shop.id] }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container shadow-lg p-3 mb-3 bg-primary-subtle rounded">
  <div class="container shadow-lg p-3 bg-primary-subtle rounded">
    <p class="h3 fw-bold mb-5">プロフィール編集</p>
    <%= form_with model: @user do |f| %>
      <div class="mb-3 col-12 text-start">
        <p class="h5 fw-bold">プロフィール画像</p>
        <%= f.file_field :avatar, class: "form-size d-grid col-12" %>
      </div>
      <% if @user.email == 'guest@example.com'%>
        <p>ゲストユーザーはユーザー情報の編集ができません。</p>
      <% else %>
        <div class="mb-3 col-12 text-start">
          <%= f.label :name , class: "form-label Form__label--required fw-bold fs-5" do %>
            <span class="text-danger">*</span> 名前
          <% end %>
          <%= f.text_field :name, class: "form-size d-grid col-12" %>
        </div>
        <div class="mb-3 col-12 text-start">
          <%= f.label :email , class: "form-label Form__label--required fw-bold fs-5" do %>
            <span class="text-danger">*</span> メールアドレス
          <% end %>
          <%= f.text_field :email, class: "form-size d-grid col-12" %>
        </div>
        <div class="mb-3 col-12 text-start">
          <%= f.label :introduction ,"ひとこと紹介文", class: "form-label Form__label--required fw-bold fs-5" %>
          <%= f.text_area :introduction, class: "form-size d-grid col-12 mb-5" %>
        </div>
      <% end %>
      <%= f.submit "編集を完了する", class: "col-12 col-md-5 btn btn-primary mb-3" %>
      <%= link_to "プロフィールへ戻る", user_path(current_user), class: "col-12 col-md-5 btn btn-primary mb-3" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container shadow-lg p-3 mb-5 bg-primary-subtle rounded">
  <div class="container shadow-lg p-3 bg-primary-subtle rounded">
    <p class="display-3 mb-5 font_design mx-auto">MINI4WD SPEED KING</p>
    <p class="fw-bold">MINI4WD SPEED KINGでは、自分の作ったミニ四駆を登録！</p>
    <p class="mb-5 fw-bold">さらにアプリ登録店へのラップタイムの投稿がどこでも簡単にできるぞ！</p>
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators d-none d-md-block">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="<%= @defaults[1].default_image %>" class="img-size border border-primary border-4 border-opacity-75 rounded" alt="...">
          <div class="carousel-caption">
            <p class="h4 bg-secondary col-8 mx-auto d-none d-md-block">マシン情報</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="<%= @defaults[4].default_image %>" class="img-size border border-primary border-4 border-opacity-75 rounded" alt="...">
          <div class="carousel-caption">
            <p class="h4 bg-secondary col-8 mx-auto d-none d-md-block">ラップタイム情報</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="<%= @defaults[2].default_image %>" class="img-size border border-primary border-4 border-opacity-75 rounded" alt="...">
          <div class="carousel-caption">
            <p class="h4 bg-secondary col-8 mx-auto d-none d-md-block">店舗情報</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="<%= @defaults[3].default_image %>" class="img-size border border-primary border-4 border-opacity-75 rounded" alt="...">
          <div class="carousel-caption">
            <p class="h4 bg-secondary col-8 mx-auto d-none d-md-block">コースレイアウト情報</p>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    <%= link_to "ログイン", new_user_session_path, class: 'post btn btn-primary d-grid col-md-6 mx-auto mb-2 mt-4' %>
    <%= link_to "新規登録", new_user_registration_path, class: 'post btn btn-primary d-grid col-md-6 mx-auto mb-2' %>
    <%= link_to 'ゲストログインはこちら', guest_login_path, method: :post, class: 'post btn btn-primary d-grid col-md-6 mx-auto' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container shadow-lg p-3 mb-5 bg-primary-subtle rounded">
  <div class="container shadow-lg p-3 bg-primary-subtle rounded">
    <div class="row bg-primary mb-4 border border-info rounded">
      <div class="d-md-flex flex-row">
        <% if @user.avatar? %>
          <%= image_tag @user.avatar.url, size: "75x75", class:'icon mt-2' %>
        <% else %>
          <%= image_tag (@defaults[0].default_image), size: "75x75", class:'icon mt-2' %>
        <% end %>
      </div>
      <p class="h2 text-md-start text-light"><%= @user.name %></p>
      <% if current_user && current_user.introduction.present? %>
        <p class="text-md-start text-light"><%= @user.introduction %></p>
      <% end %>
      <%= link_to "フォロー", user_followings_path(@user.id), class: "col-10 col-md-5 btn btn-light btn-outline-dark mx-auto fw-bold mb-3" %>
      <%= link_to "フォロワー", user_followers_path(@user.id), class: "col-10 col-md-5 btn btn-light btn-outline-dark mx-auto fw-bold mb-3" %>
      <% if current_user.email != @user.email %>
        <% if current_user.following?(@user) %>
          <%= link_to "フォロー解除", user_relationships_path(@user.id), method: :delete, class: "col-10 col-md-11 btn btn-light btn-outline-dark mx-auto fw-bold mb-3" %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "col-10 col-md-11 btn btn-light btn-outline-dark mx-auto fw-bold mb-3" %>
        <% end %>
        <% if current_user != @user && current_user.following?(@user) && @user.following?(current_user) %>
          <%= link_to 'チャットを始める', chat_path(@user.id), class: "col-10 col-md-11 btn btn-light btn-outline-dark mx-auto fw-bold mb-3" %>
        <% end %>
      <% end %>
    </div>
    <div class="container col-12 col-md-11 mb-5">
      <div class="card mb-3 col">
        <div class="row g-0">
          <div class="col-md-6">
            <div class="card">
              <% if @machines.present? %>
                <% @machines.each do |machine| %>
                  <% if machine.machine_image.present? %>
                    <%= image_tag machine.machine_image, class: 'img-fluid' %>
                  <% else %>
                    <%= image_tag(@defaults[0].default_image, style: "height: 210px;") %>
                  <% end %>
                <% end %>
              <% else %>
                <%= image_tag(@defaults[0].default_image, style: "height: 210px;") %>
              <% end %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card-body p-1">
              <% @machines.each do |machine| %>
                <h3 class="card-title bg-body-secondary">マシン名</h3>
                <p class="card-text h5 fw-bold"><%= machine.machine_name%></p>
                <h3 class="card-title bg-body-secondary mt-lg-3">マシン重量</h3>
                <p class="card-text"><small class="text-body-secondary h5 fw-bold"><%= machine.machine_weight%></small></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% if @parts.present? %>
      <div class="table_sticky shadow-lg rounded mb-4">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">カテゴリー</th>
              <th scope="col">パーツ名</th>
            </tr>
          </thead>
          <tbody>
            <% @parts.each do |part| %>
              <tr>
                <th scope="row">モーター</th>
                <td><%= part.motor_name %></td>
              </tr>
              <tr>
                <th scope="row">シャーシ</th>
                <td><%= part.chassi_name %></td>
              </tr>
              <tr>
                <th scope="row">シャフト</th>
                <td><%= part.shaft_name %></td>
              </tr>
              <tr>
                <th scope="row">プロペラシャフト</th>
                <td><%= part.propeller_name %></td>
              </tr>
              <tr>
                <th scope="row">軸受け</th>
                <td><%= part.gikuuke_name %></td>
              </tr>
              <tr>
                <th scope="row">ターミナル</th>
                <td><%= part.terminal_name %></td>
              </tr>
              <tr>
                <th scope="row">タイヤ</th>
                <td><%= part.tire_name %></td>
              </tr>
              <tr>
                <th scope="row">ホイール</th>
                <td><%= part.wheel_name %></td>
              </tr>
              <tr>
                <th scope="row">ギヤー</th>
                <td><%= part.gear_name %></td>
              </tr>
              <tr>
                <th scope="row">ローラー</th>
                <td><%= part.roller_name %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
    <% if current_user && @user == current_user %>
      <% if current_user.machines.empty? %>
        <div class="row col">
          <div class="container shadow-lg p-3 bg-primary-subtle rounded mt-3 mb-3 machine_info">
            <p class="h3 fw-bold mt-3 mb-3">マシン情報 新規登録</p>
            <%= form_with(model: @machine) do |f| %>
              <div class="mb-3 col-12 text-start">
                <p class="h5 fw-bold">マシン画像</p>
                <%= f.file_field :machine_image, class: "form-size d-grid col-12" %>
              </div>
              <div class="mb-3 col-12 text-start">
                <%= f.label :machine_name, class: "form-label Form__label--required fw-bold fs-5" do %>
                  <span class="text-danger">*</span> マシン名
                <% end %>
                <%= f.text_field :machine_name, class: "form-size d-grid col-12", placeholder: "マシン名を入力" %>
              </div>
              <div class="mb-3 col-12 text-start">
                <%= f.label :machine_weight, class: "form-label Form__label--required fw-bold fs-5" do %>
                  <span class="text-danger">*</span> マシン重量
                <% end %>
                <%= f.text_field :machine_weight, class: "form-size d-grid col-12 mb-5", placeholder: "マシン重量を入力"%>
              </div>
              <%= f.hidden_field :user_id,value: @user.id %>
              <div>
                <%= f.submit "登録完了", class: "col-5 btn btn-primary mb-3" %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
      <% if current_user.parts.empty? %>
        <div class="row col">
          <div class="container shadow-lg p-3 bg-primary-subtle rounded mt-3 mb-3 part_info">
            <p class="h3 fw-bold mt-3 mb-3">パーツ情報 新規登録</p>
            <%= form_with(model: @part, multipart: true) do |f| %>
              <div class="mb-3 col-12 text-start">
                <%= f.label :motor_name, "モーター", class: "form-label fw-bold fs-5" %>
                <%= f.select :motor_name, options_for_select(@text_options), {}, class: "form-select form-size d-grid col-12" %>
              </div>
              <div class="mb-3 col-12 text-start">
                <%= f.label :chassi_name, "シャーシ", class: "form-label fw-bold fs-5" %>
                <%= f.select :chassi_name, options_for_select(@text_options2), {}, class: "form-select form-size d-grid col-12" %>
              </div>
              <div class="mb-3 col-12 text-start">
                <%= f.label :shaft_name, "シャフト", class: "form-label fw-bold fs-5" %>
                <%= f.select :shaft_name, options_for_select(@text_options3), {}, class: "form-select form-size d-grid col-12" %>
              </div>
              <div class="mb-3 col-12 text-start">
                <%= f.label :propeller_name, "プロペラシャフト", class: "form-label fw-bold fs-5" %>
                <%= f.select :propeller_name, options_for_select(@text_options4), {}, class: "form-select form-size d-grid col-12" %>
              </div>
              <div class="mb-3 col-12 text-start">
                <%= f.label :gikuuke_name, "軸受け", class: "form-label fw-bold fs-5" %>
                <%= f.select :gikuuke_name, options_for_select(@text_options5), {}, class: "form-select form-size d-grid col-12" %>
              </div>
              <div class="mb-3 col-12 text-start">
                <%= f.label :terminal_name, "ターミナル", class: "form-label fw-bold fs-5" %>
                <%= f.select :terminal_name, options_for_select(@text_options6), {}, class: "form-select form-size d-grid col-12" %>
              </div>
              <div class="mb-3 col-12 text-start">
                <%= f.label :tire_name, "タイヤ", class: "form-label fw-bold fs-5" %>
                <%= f.select :tire_name, options_for_select(@text_options7), {}, class: "form-select form-size d-grid col-12" %>
              </div>
              <div class="mb-3 col-12 text-start">
                <%= f.label :wheel_name, "ホイール", class: "form-label fw-bold fs-5" %>
                <%= f.select :wheel_name, options_for_select(@text_options8), {}, class: "form-select form-size d-grid col-12" %>
              </div>
              <div class="mb-3 col-12 text-start">
                <%= f.label :gear_name, "ギヤー", class: "form-label fw-bold fs-5" %>
                <%= f.select :gear_name, options_for_select(@text_options9), {}, class: "form-select form-size d-grid col-12" %>
              </div>
              <div class="mb-3 col-12 text-start">
                <%= f.label :roller_name, "ローラー", class: "form-label fw-bold fs-5" %>
                <%= f.select :roller_name, options_for_select(@text_options10), {}, class: "form-select form-size d-grid col-12 mb-5" %>
              </div>
              <%= f.hidden_field :user_id,value: @user.id %>
              <div>
                <%= f.submit "登録完了", class: "col-5 btn btn-primary mb-3" %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
      <% if current_user.machines.any? %>
        <%= link_to "マシン情報 編集", edit_machine_path(current_user.machines.first.id), class: "col-8 col-md-5  btn btn-primary mx-3 mb-2 mt-2" %>
      <% end %>
      <% if current_user.parts.any? %>
        <%= link_to "パーツ情報 編集", edit_part_path(current_user.parts.first.id), class: "col-8 col-md-5  btn btn-primary mx-3 mb-5 mt-md-5" %>
      <% end %>
      <div class="row col-12 mx-auto mb-3 border rounded bg-warning-subtle">
        <p class="display-6 fw-bold mt-3">ラップタイム投稿</p>
      </div>
      <div class="dropdown col-8 mx-auto">
        <button class="btn btn-secondary btn dropdown-toggle w-100" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          店舗選択
        </button>
        <ul class="dropdown-menu dropdown-menu-dark w-100">
          <li><%= link_to "株式会社タミヤ", shop_path(@shop_categories["株式会社タミヤ"]), class: "dropdown-item" %></li>
          <li><%= link_to "小鹿第一工場", shop_path(@shop_categories["小鹿第一工場"]), class: "dropdown-item" %></li>
          <li><%= link_to "池田工場", shop_path(@shop_categories["池田工場"]), class: "dropdown-item" %></li>
          <li><%= link_to "第二物流センター", shop_path(@shop_categories["第二物流センター"]), class: "dropdown-item" %></li>
        </ul>
      </div> 
    <% end %>
    <div class="container col-12 shadow-lg p-3 bg-primary-subtle rounded mt-3">
      <p class="h3 fw-bold mt-3 mb-3">ラップタイム一覧</p>
      <table class="table">
        <thead class="table-warning">
          <tr>
            <th scope="col">店舗</th>
            <th scope="col">ユーザー</th>
            <th scope="col">タイム</th>
          </tr>
        </thead>
        <tbody>
          <% @lap_time_to_races.each do |lap| %>
            <tr>
              <td><%= link_to lap.shop.shop_name, shop_path(lap.shop) %></td>
              <td><%= lap.user.name %></td>
              <td id="lapTimeCell"><%= lap.lap_time.present? ? lap.lap_time.strftime("%H:%M:%S") : "N/A" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div> 
  </div>
</div>