config/routes.rb
Rails.application.routes.draw do
  get 'searches/index'
  root 'users#index'
  post 'guest_login', to: 'sessions#guest_login'
  
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations' 
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :chats, only: [:show, :create]
  resources :machines
  resources :lap_time_to_races
  resources :parts
  resources :shops
  resources :searches do
    collection do
      get :search
    end
  end

  get 'shops/index'
  get 'parts/index'
  get 'users/index'

end

app/views/layouts/_footer.html.erb
<footer class="bg-primary-subtle text-light py-5">
  <div class="container">
    <p class="text-dark lh-lg text-start">
      © TAMIYA 当サイト上で使用している画像の著作権および商標権、その他知的財産権は、当該コンテンツの提供元に帰属します。<br>
      © 2024 Tsukasa Ohashi
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark" >
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= new_user_session_path %>">MINI4WD SPEED KING</a>
    <div class="navbar-collapse d-lg-flex flex-lg-row-reverse">
      <ul class="navbar-nav">
        <li class="nav-item dropstart">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            メニュー
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="<%= new_user_session_path %>">マイページ</a></li>
            <li><a class="dropdown-item" href="<%= search_searches_path %>">ユーザー一覧</a></li>
            <% if current_user %>
              <li><%= link_to "プロフィール編集", edit_user_path(current_user), class: "dropdown-item" %></li>
            <% end %>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>MINI4WD SPEED KING</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body data-turbolinks="false">
    <% unless (controller_name == 'users' && action_name == 'index') || controller_path.starts_with?('devise') || (controller_name == 'sessions' && action_name == 'new') || (controller_name == 'passwords' && (action_name == 'new' || action_name == 'edit')) %>
      <%= render 'layouts/header' %>
    <% end %>
    <div class="mask d-flex" style="background-image: url(<%= @defaults[5].default_image %>); background-position: center; width: 100%; max-width: 100%;">
      <div class="mask container-fluid py-5 text-center">
        <%= yield %>
      </div>
    </div>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBJo38-EPUqWGJF5SSMsuGKo9bNAPEDFAA&callback=initMap" async defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= render 'layouts/footer' %>
  </body>
</html>